### ISSUE TITLE
Add hook to keep the 1st person view at all times

### ISSUE THREAD

**Issue by morallo** [Prof-Butts/Hook_XWACockpitLook#21]
```
<Patch Name="disable random hangar camera">
    <!-- Pre-launch -->
    <Item Offset="05B583" From="E8B83A0000" To="9090909090" />
    <!-- Launch -->
    <Item Offset="05AD61" From="E8DA420000" To="9090909090" />
    <!-- Re-enter -->
    <Item Offset="057866" From="E8D5770000" To="9090909090" />
</Patch>
```

**Comment by ual002** [comment]
Is this helpful?

<Patch Name="disable random hangar camera">
    
    <Item Offset="05B583" From="E8B83A0000" To="9090909090" />
    
    <Item Offset="05AD61" From="E8DA420000" To="9090909090" />
    
    <Item Offset="057866" From="E8D5770000" To="9090909090" />
  </Patch>

**Comment by ual002** [comment]
I approve of this.
